### ISSUE TITLE
能批量导入图片吗？

### ISSUE THREAD

**Issue by sh442399601** [alibaba/AGEIPort#10]
我们会有很多图片压缩成zip。服务端需要解压Zip，拿到一张张图片，服务将图片一张张上传到文件中心获得文件ID，根据规则解析图片名称，将文件ID按照要求存库。不知道这个框架能否导入含有图片的ZIP包

**Comment by ZeganLi** [comment]
同问，我们这边也会有很多的自定义编码格式的文件，需要大量的导入与导出。不止只有图片，还有视频等其他。

**Comment by clsaa** [comment]
这个可以支持，文件读写用的是一个SPI，下周写一个基本的demo出来
