### ISSUE TITLE
导出示例问题一大堆 遇到的问题的解决办法  最后 建议文档进行修改以及完善 

### ISSUE THREAD

**Issue by silent-night-no-trace** [alibaba/AGEIPort#13]
1、TestHelper中 assertWithFile和assertWithoutFile 方法中 GetTaskProgressParam 这个类有误
解决办法： 将其修改为TaskProgressParam  而不是GetTaskProgressParam
2、重点 扩展类找不到  文档中的描述 
1. 项目目录的resources文件夹下创建META-INF文件夹
2. META-INF文件夹下创建名为com.alibaba.ageiport.processor.core.Processor的文本文件
解决办法 一路debug下去发现 扩展类要放到 resources/META-INF/ageiport 目录下扩展类才能被加载到
![image](https://user-images.githubusercontent.com/21052733/208236908-32c92fa5-34f9-4146-9313-57e778eed01f.png)

可使用如下方式测试扩展有无加载成功
```java
@Slf4j
public class StandaloneExportProcessorTest {
   
    @Test
    public void test1() {
        Set<Processor> instances = ExtensionLoader.getExtensionLoader(Processor.class).getSupportedExtensionInstances();
        log.info(instances);
    }
}
```
也可以查看打印的示例是否是自己的
3、导出测试类中报错 
```java
AgeiPortOptions.Debug debug = new AgeiPortOptions.debug();
#不存在这个属性。。
options.setDebug(debug);
```
解决办法：注释掉即可
3、依赖下载不到  （可能是网络原因？）
```xml
<dependency>
    <groupId>com.alibaba</groupId>
    <artifactId>ageiport-processor-core</artifactId>
    <version>0.0.1-SNAPSHOT</version>
    <scope>compile</scope>
</dependency>
```
官方文件推荐如上 依赖无法下载 
解决办法：源码构建  在主pom ageiport-parent 中注释掉maven的插件 maven-gpg-plugin 和 maven-javadoc-plugin （可选 不然可能遇到很多坑。。需要使用经验）
源码构建成功 install到本地 可直接使用
```xml
<dependency>
      <groupId>com.alibaba</groupId>
      <artifactId>ageiport-processor-core</artifactId>
      <version>0.0.4</version>
      <scope>compile</scope>
</dependency>
```
4、示例无法跑起来 以及没有正确的配置步骤 
遇到agei-server-task 未配置的问题

**Comment by silent-night-no-trace** [comment]
<img width="891" alt="WeChat0326df1eda60658b337a13cecc6e4551" src="https://user-images.githubusercontent.com/21052733/208236931-90921517-155c-4611-83d1-38fc1ef8f888.png">

**Comment by clsaa** [comment]
示例文档可能和代码不match了，我后续会整理简化下文档，引导直接运行项目里的测试用例
