### ISSUE TITLE
能否增加配置，可以自定义文件导出位置，以及增加导出csv类型

### ISSUE THREAD

**Issue by xjxjin** [alibaba/AGEIPort#15]
能否增加配置，可以自定义文件导出位置
能否增加默认导出类型csv

**Comment by clsaa** [comment]
没太理解自定义文件导出的位置是指？
CSV格式是可以增加和支持的，文件读写有一个SPI，只需要扩展这个SPI即可，我本周可以加一个demo在里面

**Comment by xjxjin** [comment]
<img width="933" alt="image" src="https://user-images.githubusercontent.com/35513148/209027163-7c40bd83-72b2-4a09-a57c-6da5c6585756.png">

此处位置是固定的为user.home/agei/xxx.xlsx，能否修改成可配置的，自己指定生成的文件路径。
以及自己给定文件名生成规则，比如固定前缀+日期时间+随机数等之类的

**Comment by XingDunguo** [comment]
请教一下，这个组件具体该如何使用

**Comment by iYaDongWang** [comment]
你好，如果是使用LocalStore进行写文件，可以通过设置LocalFileStoreOptions的basePath属性达到修改文件导出位置的目的。
![image](https://user-images.githubusercontent.com/38178396/210951462-4e08a91b-8f8f-42fc-bab8-f4e9cfc14f75.png)

**Comment by clsaa** [comment]
麻烦看下上边其他同学的回复哈，但一般在生产环境会将文件存在OSS而不是本地
