### ISSUE TITLE
感觉缺少一个tenant字段

### ISSUE THREAD

**Issue by hadoop835** [alibaba/AGEIPort#18]
![image](https://user-images.githubusercontent.com/8055054/210481305-a8205e73-b37f-4065-8d1e-cecaf2a67fe9.png)
![image](https://user-images.githubusercontent.com/8055054/210481642-6cdafdb3-37e4-44f4-a811-8bac2754149f.png)

**Comment by clsaa** [comment]
一般accessKeyId就对应了一个租户 or 用户， 不需要用户在客户端再配置其他租户 or 用户的信息
