### ISSUE TITLE
您好，请问一下合并行合并列怎么做啊，文档没有找到相关的api

### ISSUE THREAD

**Issue by chenflappy** [alibaba/AGEIPort#19]

**Comment by XingDunguo** [comment]
请教一下，这个组件具体该如何使用

**Comment by clsaa** [comment]
如果是表头合并：默认当相邻表头值相同时会自动合并，参考用例：com.alibaba.ageiport.test.processor.core.exporter.StandaloneExportProcessorTest，中com.alibaba.ageiport.test.processor.core.model.View的定义

如果是是数据合并：需要自定义单元格样式，参考用例：com.alibaba.ageiport.test.processor.core.exporter.ExcelStyleExportProcessorTest，文档:https://github.com/hadoop835/AGEIPort/blob/master/docs/zh/%E8%87%AA%E5%AE%9A%E4%B9%89%E8%BE%93%E5%87%BAExcel%E6%96%87%E4%BB%B6%E6%A0%B7%E5%BC%8F.md
