### ISSUE TITLE
第3步，运行单元测试，执行任务时报空指针异常

### ISSUE THREAD

**Issue by andy-yc** [alibaba/AGEIPort#2]
![image](https://user-images.githubusercontent.com/82647364/193008790-311e8853-7d5d-4cd2-be6d-133ad2432058.png)
完全按照文档来写的，运行单测的时候就报这个NPE

**Comment by andy-yc** [comment]
![image](https://user-images.githubusercontent.com/82647364/193009101-23ccb77e-a603-4c10-b0c7-07ba4d2f027d.png)
这里编译都通不过，依赖都引了，查看源码里AgeiPortOptions的Debug类是私有的，AgeiPortOptions也没有debug属性

**Comment by RuiZhang-cn** [comment]
我也是,报错代码是 `TaskSpec taskSpec = registry.get(code);` taskSpec  这个对象为null,registry 是`TaskSpecificationRegistry registry = ageiPort.getSpecificationRegistry();`
文件路径:
ageiport-processor-core-0.0.1-sources.jar!/com/alibaba/ageiport/processor/core/spi/service/TaskServiceImpl.java:40

**Comment by clsaa** [comment]
@RuiZhang-cn 请问是直接运行的单元测试吗？如果是自己写的代码要注意编写注册Handler的配置文件，配置文件名是 com.alibaba.ageiport.processor.core.Processor，可以参考单元测试类的编写

**Comment by clsaa** [comment]
@andy-yc 麻烦重新拉master的最新代码看是否有编译错误？

**Comment by clsaa** [comment]
正式包版本0.0.4已解决，可以拉最新代码运行单元测试

**Comment by linxxxyz** [comment]
我运行com.alibaba.ageiport.test.processor.core.importer.StandaloneImportProcessorTest#test 提示“File and inputStream must be a non-null.”，解决方法是：com.alibaba.ageiport.task.server.model.CreateMainTaskInstanceRequest 类下缺少了feature（扩展属性）参数，导致com.alibaba.ageiport.processor.core.spi.client.CreateMainTaskRequest下的feature无法传输到server，加上就可以正常运行了
