### ISSUE TITLE
同一个子任务ID会导致覆盖，

### ISSUE THREAD

**Issue by hadoop835** [alibaba/AGEIPort#20]
![image](https://user-images.githubusercontent.com/8055054/210761031-ae3df0eb-7e69-4f39-b8eb-5e8637a8777f.png)
![image](https://user-images.githubusercontent.com/8055054/210761135-e15705ac-c672-4cef-b1da-f5574a3aa44f.png)
![image](https://user-images.githubusercontent.com/8055054/210762189-ceaed887-9696-4588-9808-6190d5ea456e.png)

**Comment by clsaa** [comment]
没太明白问题是？ subTaskProgressMap里存的就是子任务最新的状态，后续再根据subTaskProgressMap里子任务的状态判断主任务什么时候应该reduce

**Comment by hadoop835** [comment]
@clsaa 
![image](https://user-images.githubusercontent.com/8055054/210937028-576837bd-6ba3-4f52-89c2-ad90e2ba16b6.png)
你看一下这个逻辑，只有子任务完成subTaskProgress.getIsFinished()才是true。其他都是false。会导致map的key相同被覆盖

**Comment by clsaa** [comment]
此问题应该被修复了，由于任务状态事件是无序的，原本有个逻辑会导致  子任务被改为finished状态后又被覆盖为executing状态。最终导致判断失败。目前此问题已修复
