### ISSUE TITLE
你好，可以支持下表头合并嘛，如下图

### ISSUE THREAD

**Issue by XiaoStack** [alibaba/AGEIPort#26]
![image](https://user-images.githubusercontent.com/56242652/211497360-35345263-e363-486c-a766-bb7563d46b9f.png)

**Comment by clsaa** [comment]
你好，这个是支持的，参考测试用例中View的配置
com.alibaba.ageiport.test.processor.core.model.View

<img width="758" alt="image" src="https://user-images.githubusercontent.com/32028545/215311934-b359339a-10ac-4df8-a14a-2be2a9fab92b.png">
