### ISSUE TITLE
LocalMemoryBigDataCache导致的内存泄露

### ISSUE THREAD

**Issue by iYaDongWang** [alibaba/AGEIPort#28]
在执行Standalone模式的Processor时，subtask使用LocalMemoryBigDataCache作为缓存，但是在MainTask进行merge操作之后，并没有清理缓存，最终导致这部分内存无法回收。
com.alibaba.ageiport.processor.core.task.exporter.worker.ExportMainTaskWorker#doReduce
![image](https://user-images.githubusercontent.com/38178396/212867284-d71801c8-3181-41ee-99cb-105218a68e3d.png)

Jprofiler的最大对象显示LocalMemoryBigDataCache占用内存
![image](https://user-images.githubusercontent.com/38178396/212867439-7961ddca-76de-475a-be4d-dba24b964770.png)
老年代内存占满，且gc无法回收这部分内存
![image](https://user-images.githubusercontent.com/38178396/212867655-9a190a69-8d47-42a9-9376-1dda3bfe1af6.png)

**Comment by clsaa** [comment]
已修复，版本号0.1.1
