### ISSUE TITLE
EventBusManager 类代码存在错误

### ISSUE THREAD

**Issue by hongmengfu** [alibaba/AGEIPort#32]
![image](https://user-images.githubusercontent.com/39451856/219556719-ac44bcc4-6af3-482d-ae8a-b9dad108c57c.png)

EventBusOptions clusterEventBusOptions = options.getLocal().getEventBusOptions();
应该是 EventBusOptions clusterEventBusOptions = options.getCluster().getEventBusOptions();

**Comment by clsaa** [comment]
已经修复此问题版本号：0.1.9
