### ISSUE TITLE
关于使用的一些问题请教

### ISSUE THREAD

**Issue by XiaoStack** [alibaba/AGEIPort#35]
1.测试类中的示例最终好像都是基于反射调用的，这样对于使用 spring 管理的 bean（比如使用 @Resource 或者 @Autowired 修饰），反射构建执行时会报出空指针，因此需要对实现类做特殊处理，请问有比较优雅的使用示例嘛，求解
![image](https://user-images.githubusercontent.com/56242652/220615097-9d7b4505-72c2-4b29-8282-869bef751410.png)

2.测试示例的使用方式就是生产使用的最终形态嘛，是否有其他构建和调用的方式，如果有，方便给出示例不
![image](https://user-images.githubusercontent.com/56242652/220615934-225ee32e-b706-4464-a78e-637a5db9c2c7.png)

**Comment by clsaa** [comment]
代码中没有使用反射，如果你使用了Spring的Bean，可以把AgeiPort看成 一个Bean，在Configuration里初始化。随后你可以在其他的Spring代码中比如IMPORTController中使用AgeiPort创建导入导出任务
