### ISSUE TITLE
导入时存在错误数据并设置导出错误数据时有问题

### ISSUE THREAD

**Issue by lailailai1203** [alibaba/AGEIPort#40]
在分为多片导入时，其中一个子任务存在错误，并将错误数据进行导出时，主任务结束后
com.alibaba.ageiport.processor.core.task.importer.worker.ImportMainTaskWorker#doReduce方法中
<img width="907" alt="image" src="https://user-images.githubusercontent.com/49483297/223934667-fe5f9daa-b579-4ff5-84d6-ac2c10343eb5.png">
由于循环导致最后的existView变量为false而无法生成错误数据的文件。

**Comment by clsaa** [comment]
一个子任务错误则会导致主任务错误，主任务的状态会变为ERROR

**Comment by lailailai1203** [comment]
我是在ImportProcessor的write方法中进行try-catch，在捕获到异常的时候使用BizImportResultImpl的setView方法进行存储错误的数据，按理说应该可以在主任务结束的时候导出错误数据的excel，但是由于图上的逻辑，导致错误数据的excel没有生成。
