### ISSUE TITLE
关于ImportMainTaskWorker.doReduce()方法中onFinished(context)方法的调用逻辑的问题

### ISSUE THREAD

**Issue by QQ502130297** [alibaba/AGEIPort#43]
问题：只要主任务不抛异常onFinished(context)就会执行，MainTask就会被设置finish状态。并没有判断是否有子任务执行失败的情况。
![image](https://user-images.githubusercontent.com/76637954/225829469-780db50f-a7f2-417a-ad26-b3427046cef4.png)

上图的MainTask.state=error（子任务执行失败导致），但是还是执行了onFinished(context)方法。

**Comment by love9971** [comment]
我理解的 onFinished 表示的是此次导入/导入任务是否完成，成功/失败是状态，并不是只有成功才算完成。

**Comment by love9971** [comment]
您好，邮件已收到。
