### ISSUE TITLE
ImportProcessor返回的View数据, 无法生成文件

### ISSUE THREAD

**Issue by QQ502130297** [alibaba/AGEIPort#46]
[ImportMainTaskWorker.java](https://github.com/alibaba/AGEIPort/blob/master/ageiport-processor/ageiport-processor-core/src/main/java/com/alibaba/ageiport/processor/core/task/importer/worker/ImportMainTaskWorker.java)中doReduce()中对existView赋值逻辑有误，导致View数据, 无法生成文件
![image](https://user-images.githubusercontent.com/76637954/226562068-85fac6b6-83e4-43b9-b185-b88633c74d86.png)

验证
前提：只有两个子任务
测试代码基于[ClusterImportProcessorTest.java](https://github.com/alibaba/AGEIPort/blob/master/ageiport-test/ageiport-test-processor-core/src/test/java/com/alibaba/ageiport/test/processor/core/importer/ClusterImportProcessorTest.java)改造
```java
public BizImportResult<View, Data> convertAndCheck(BizUser user, Query query, List<View> views) {
      BizImportResultImpl<View, Data> result = new BizImportResultImpl<>();

      List<Data> data = new ArrayList<>();
      for (View view : views) {
          Data datum = new Data();
          datum.setId(view.getId());
          datum.setName(view.getName());
          datum.setGender(view.getGender());
          data.add(datum);
      }

      result.setData(data);
      ImportSubTaskContextImpl context = getContext();
      String subTaskId = context.getSubTask().getSubTaskId();
      String no = subTaskId.substring(subTaskId.lastIndexOf("_") + 1);
      // 第一个子任务输出View
      if ("1".equals(no)){
          result.setView(views);
      }else{
          // 最后一个子任务没有输出View
          result.setView(new ArrayList<>());
      }
      return result;
  }
```
导入测试文件[ClusterImportProcessor.xlsx](https://github.com/alibaba/AGEIPort/files/11026668/ClusterImportProcessor.xlsx)

测试结果：
![image](https://user-images.githubusercontent.com/76637954/226564529-0286d3d9-241a-49ba-98b2-82edb7dee494.png)
![image](https://user-images.githubusercontent.com/76637954/226564855-dd7ddd69-5601-466c-afda-84a70c05271a.png)

**Comment by clsaa** [comment]
此问题已修复，版本0.2.3
