### ISSUE TITLE
疑问：架构图中所指子任务全部执行完成执行合并操作，是指子任务全部执行成功还是子任务全部执行完（包含成功失败）

### ISSUE THREAD

**Issue by QQ502130297** [alibaba/AGEIPort#47]
相关代码 [TaskProgressMonitorImpl.java](https://github.com/alibaba/AGEIPort/blob/master/ageiport-processor/ageiport-processor-core/src/main/java/com/alibaba/ageiport/processor/core/task/monitor/TaskProgressMonitorImpl.java)
![image](https://user-images.githubusercontent.com/76637954/226567235-76a1982e-dba8-43e0-94cb-2f1b1321b2c4.png)
子任务执行失败是否需要执行合并操作

**Comment by clsaa** [comment]
子任务执行完，包含成功和失败会执行reduce，但reduce时 如果有存在失败的子任务reduce时会任务主任务失败，整个任务置为失败，不会合并
