### ISSUE TITLE
AGEI中主任务和子任务的监控

### ISSUE THREAD

**Issue by love9971** [alibaba/AGEIPort#48]
1. 子任务节点挂掉的处理
2. 子任务失败部分的处理

请问这部分的监控是不是还没完善；

**Comment by clsaa** [comment]
我们一般认为导入导出是一个业务操作，如果子任务节点挂掉，用户重新导入即可，重新导入后 任务会被分配到存活的节点。

子任务失败则认为整个任务失败。

**Comment by love9971** [comment]
您好，邮件已收到。
