### ISSUE TITLE
主节点异常出产生垃圾数据，导致任务一直在运行中的状态

### ISSUE THREAD

**Issue by zhouganqing** [alibaba/AGEIPort#49]
比如某主节点有三个主任务在执行中，服务发版了，就会导致这三个任务都一直在运行中，未执行最终态闭环。数据库会留下很多垃圾数据，有全链路闭环的Demo吗？

**Comment by clsaa** [comment]
这个可以通过数据库脚本，或者应用程序定时任务去清理状态哈
