### ISSUE TITLE
集群模式下，主节点会把子任务分割，然后调用集群机器分配，这块怎么没看到子任务处理的逻辑

### ISSUE THREAD

**Issue by 810230010** [alibaba/AGEIPort#54]
![image](https://user-images.githubusercontent.com/16313914/235112554-02c745fe-47ef-4c2a-afc0-a1413b92eb7f.png)
发送给集群机器，调用/subTasks接口，意思是集群机器提供/subTasks的http接口吗

**Comment by clsaa** [comment]
对的，通过HTTP接口推送子任务
