### ISSUE TITLE
主任务中的数据总量data_total_count 没有使用吗？

### ISSUE THREAD

**Issue by xiTingZuiBian** [alibaba/AGEIPort#63]
default void onFinished(TaskContext context) {
        getMgeiPort().getMainTaskCallback().beforeFinished(getMainTask());
        MainTask contextMainTask = context.getMainTask();
        contextMainTask.setStatus(TaskStatus.FINISHED);
        contextMainTask.setSubSuccessCount(contextMainTask.getSubTotalCount());
        contextMainTask.setSubFinishedCount(contextMainTask.getSubTotalCount());
        contextMainTask.setGmtFinished(new Date());
        contextMainTask.setDataSuccessCount(contextMainTask.getDataTotalCount());
        contextMainTask.setDataProcessedCount(contextMainTask.getDataTotalCount());
        context.save();
        getMgeiPort().getMainTaskCallback().afterFinished(getMainTask());
    }

只看到获取总数去设置其他，没有看到总数是何时设置进去的，目前看来没有使用到？

**Comment by clsaa** [comment]
是的，目前这个字段没有使用
