### ISSUE TITLE
集群模式导出时，合并文件阶段没办法获取远程节点上的缓存，报空指针

### ISSUE THREAD

**Issue by kaysonsun** [alibaba/AGEIPort#68]
报空指针的业务代码位置
![image](https://github.com/user-attachments/assets/ba905a6a-739f-4b62-a485-d07b0c82cd70)
看源码获取到的cache是这个类，但是这个类的put方法仅仅把当前节点分片的数据缓存下来了，没有缓存其他节点的子任务
![image](https://github.com/user-attachments/assets/1680a1c7-a677-46d9-b5b7-fc8cc6edcf98)

**Comment by kaysonsun** [comment]
filestore换成oss了，这个先关闭

**Comment by jianming007** [comment]
@kaysonsun 想问一下, 换到oss确实没问题, 但是为什么集群上却只有一台机器再运行呢?
