### ISSUE TITLE
请教

### ISSUE THREAD

**Issue by Flower0313** [alibaba/AGEIPort#7]
开发者，你好，我完全按照你的导出示例来跑，还是会报出：`java.lang.NullPointerException: null
	at com.alibaba.ageiport.processor.core.spi.service.TaskServiceImpl.executeTask(TaskServiceImpl.java:41)`的错误，名称我都核对了，请问为啥呢？

**Comment by Flower0313** [comment]
好像是在执行任务的时候出错，META-INF文件也加了，也是用的自己的全类名

**Comment by QianZuiJava** [comment]
![image](https://user-images.githubusercontent.com/69590379/207766356-1eb4cbdd-f62a-4320-a943-7f1c8215f0a0.png)
要在META-INF 下在新建一个 ageiport ，然后在此目录下添加注册文件。
对比原始包结构
![image](https://user-images.githubusercontent.com/69590379/207766554-362def00-dac5-4bcc-b689-c07a801af0d9.png)

**Comment by clsaa** [comment]
参考下上边同学的回复噢

**Comment by QianZuiJava** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，现在我不在，看到后会尽快给您回复。                                                   ———棒棒
