### ISSUE TITLE
clone了master，pom文件报错

### ISSUE THREAD

**Issue by zk11231002** [alibaba/AGEIPort#8]
clone了master，pom文件报错，很多依赖找不到

**Comment by clsaa** [comment]
具体是什么依赖找不到，二方包还是三方包？Maven中心仓库可以搜到吗？

**Comment by Eeearth-Van** [comment]
我之前貌似有同样的问题，clone项目后部分模块的`io.quarkus`依赖下不动。后面我把全局编译器指定JDK17，重新`mvn clean`能下了。

我这还有个问题，想请教这个源码要怎么编译呢？有依赖还会报错，是需要执行什么命令嘛？太高级了搞不懂求指点😂
![image](https://user-images.githubusercontent.com/29729480/207786073-3b867ead-756f-44ce-a7ad-4c7075da3cb9.png)

**Comment by Eeearth-Van** [comment]
> 我之前貌似有同样的问题，clone项目后部分模块的`io.quarkus`依赖下不动。后面我把全局编译器指定JDK17，重新`mvn clean`能下了。
> 
> 我这还有个问题，想请教这个源码要怎么编译呢？有依赖还会报错，是需要执行什么命令嘛？太高级了搞不懂求指点😂 !
解决了，mvn导入的版本也要就修改下。
![image](https://user-images.githubusercontent.com/29729480/207885067-68ecdd1f-6eee-4ac0-b6ee-66a86004880d.png)

**Comment by clsaa** [comment]
需要指定JDK17噢~
